auto-sync.sh 2018-06-03 06:52:35: 6 file/s changed
Syncing log
------------
X11 forwarding request failed on channel 0
Los ficheros /home/boret/src/scripts-config-dotfiles/.i3/wallpapers.txt y /home/boret/.i3/wallpapers.txt son distintos
'/home/boret/.i3/wallpapers.txt' -> '/home/boret/src/scripts-config-dotfiles/.i3/wallpapers.txt'
--------------------------------
/usr/bin/diff: /home/boret/LICENSE: No existe el fichero o el directorio
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/scripts/src_updater.sh y /home/boret/sbin/src_updater.sh son distintos
'/home/boret/sbin/src_updater.sh' -> '/home/boret/src/scripts-config-dotfiles/scripts/src_updater.sh'
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/scripts/script-funcs.sh y /home/boret/sbin/script-funcs.sh son distintos
'/home/boret/sbin/script-funcs.sh' -> '/home/boret/src/scripts-config-dotfiles/scripts/script-funcs.sh'
--------------------------------
/usr/bin/diff: /home/boret/.config/plasma-workspace/env/wm.sh: No existe el fichero o el directorio
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/.config/i3/config y /home/boret/.config/i3/config son distintos
'/home/boret/.config/i3/config' -> '/home/boret/src/scripts-config-dotfiles/.config/i3/config'
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/.config/ranger/tagged y /home/boret/.config/ranger/tagged son distintos
'/home/boret/.config/ranger/tagged' -> '/home/boret/src/scripts-config-dotfiles/.config/ranger/tagged'
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/.config/compton/compton.conf y /home/boret/.config/compton/compton.conf son distintos
'/home/boret/.config/compton/compton.conf' -> '/home/boret/src/scripts-config-dotfiles/.config/compton/compton.conf'
--------------------------------

diff --git a/.config/i3/config b/.config/i3/config
--- a/.config/i3/config
+++ b/.config/i3/config
@@ -326,6 +326,7 @@ bar {
 
 exec --no-startup-id "/home/boret/.i3/init_ws -w '1: Init' \
 	     -l '/home/boret/.i3/testing_2.json' \
+	     -c '/usr/bin/conky -c /home/boret/.i3/conky_motorhead.conf' \
 	     -c '/home/boret/.i3/fehbg_new' \
 	     -c '/home/boret/.i3/termite_wrap -t ranger -e ranger' \
 	     -c '/home/boret/.i3/termite_wrap -t Terminal'"
@@ -334,16 +335,16 @@ exec --no-startup-id "/home/boret/.i3/init_ws -w '1: Init' \
 #
 # Run compton_wrap once conky cheats have been called
 #
-#exec --no-startup-id "while ! pgrep conky >/dev/null 2>&1; \
-			#do \
-				#echo ' -- i3 launch --> waiting for conky'; \
-				#sleep 1; \
-				#count=$count+1; \
-				#if [ $count -gt 5 ]; \
-					#then echo ' -- i3 launch --> conky seems to have failed'; \
-					#break; \
-				#fi; \
-			#done; \
-			#sleep 3; \
-exec --no-startup-id "sleep 2s; /home/boret/.i3/compton_wrap"
-exec --no-startup-id "sleep 3s; terminator -T 'fetchscr' -p 'transparent' -e 'screenfetch -p'"
+exec --no-startup-id "while ! pgrep conky >/dev/null 2>&1; \
+			do \
+				echo ' -- i3 launch --> waiting for conky'; \
+				sleep 1; \
+				count=$count+1; \
+				if [ $count -gt 5 ]; \
+					then echo ' -- i3 launch --> conky seems to have failed'; \
+					break; \
+				fi; \
+			done; \
+			sleep 1; \
+			/home/boret/.i3/compton_wrap -f"
+#exec --no-startup-id "sleep 3s; terminator -T 'fetchscr' -p 'transparent' -e 'screenfetch -p -c 15,9 -a /home/boret/motorhead_ascii_2'"
