auto-sync.sh 2018-01-07 14:46:57: 2 file/s changed
Syncing log
------------
X11 forwarding request failed on channel 0
/usr/bin/diff: /home/boret/LICENSE: No existe el fichero o el directorio
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/scripts/docker_run y /home/boret/sbin/docker_run son distintos
'/home/boret/sbin/docker_run' -> '/home/boret/src/scripts-config-dotfiles/scripts/docker_run'
--------------------------------
Los ficheros /home/boret/src/scripts-config-dotfiles/scripts/script-funcs.sh y /home/boret/sbin/script-funcs.sh son distintos
'/home/boret/sbin/script-funcs.sh' -> '/home/boret/src/scripts-config-dotfiles/scripts/script-funcs.sh'
--------------------------------

diff --git a/scripts/docker_run b/scripts/docker_run
--- a/scripts/docker_run
+++ b/scripts/docker_run
@@ -1,4 +1,7 @@
 #!/bin/bash
+#
+# A dialog based script to run locally stored docker images
+#
 
 DIALOG=/usr/bin/dialog
 
@@ -19,11 +22,10 @@ SIG_TERM=15					#
 declare -a IMG_REPO=( $(docker images |awk '{printf "%s ", $1}') )
 declare -a IMG_TAG=( $(docker images |awk '{printf "%s ", $2}') )
 declare -a IMG_ID=( $(docker images |awk '{printf "%s ", $3}') )
+declare -a IMAGE
 _backtitle="dialog based Docker images launcher by boret"
-VOLUME=""
-CON_NAME=""
-COMMAND="docker run"
 tempfile=/tmp/test$$
+INPUT_F=/tmp/test_$$
 
 #############################################################################
 #				Trap signals				    #
@@ -37,6 +39,8 @@ exec 4<>$tempfile
 #				Functions				    #
 #############################################################################
 
+# Utility to fill the dialog menu entries with local images
+#
 fill_repos()
 {
 	let n=1
@@ -46,6 +50,9 @@ fill_repos()
 	done
 }
 
+# check the return code of a dialog item to abort script
+# parameters $1 = return code (usually $?)
+#
 get_result()
 {
 	case $1 in
@@ -55,6 +62,9 @@ get_result()
 	esac
 }
 
+# a dialog to get data if we want to mount a volume
+# fill VOLUME global variable
+#
 volume_form()
 {
 	$DIALOG --clear  --backtitle "$_backtitle" --title " Punto de montaje " \
@@ -72,6 +82,9 @@ volume_form()
 ' -f3 $tempfile)"
 }
 
+# a dialog to get the desired name of a container
+# sets a global variable CON_NAME
+#
 name_form()
 {
 	$DIALOG --clear --backtitle "$_backtitle" --title " Nombre del contenedor " \
@@ -83,7 +96,19 @@ name_form()
 	CON_NAME="$(cat $tempfile)"
 }
 
-# Load functions library
+# output to stdout the name of an image, given its sha
+# parameters: $1 = image sha
+#
+image_name()
+{
+	local i=0
+	while [[ $i -lt ${#IMG_ID[@]} ]]; do
+		[[ $1 == "${IMG_ID[$i]}" ]] && echo "${IMG_REPO[$i]}"
+		(( i++ ))
+	done
+}
+
+# Source functions library
 . $HOME/sbin/script-funcs.sh
 
 #############################################################################
@@ -91,57 +116,75 @@ name_form()
 #############################################################################
 get_term_size _H _W
 
-$DIALOG --clear --backtitle "$_backtitle" --title " Imágenes disponibles " \
-	--menu "Selecciona la imagen:" $((_H/2)) $((_W/2)) 8 \
-	$(fill_repos) 2> $tempfile
+case $# in
+	0)   $DIALOG --clear --backtitle "$_backtitle" --title " Imágenes disponibles " \
+		--menu "Selecciona la imagen:" $((_H/2)) $((_W/2)) 8 \
+		$(fill_repos) 2> $tempfile
+	     get_result $?
+	     IMAGE=( $(cat "$tempfile") )
+	     ;;
+        1)   IMAGE=( $1 )
+	     ;;
+	*)   $DIALOG --clear --backtitle "$_backtitle" --colors --title " \Zb\Zu\Z1AVISO\Zn " \
+		--msgbox "\Z1Se ha solicitado más de una imagen.\Zn
+Asegúrate de que la opción \Z1--detach\Zn se activa en los siguientes menús" $((_H/2)) $((_W/2))
+	     IMAGE=( $@ )
+	     ;;
+esac
+i=0
+while (( i < ${#IMAGE[@]} )); do
+	VOLUME=""
+	CON_NAME=""
+	COMMAND="docker run"
+	j=0
+	$DIALOG --clear --backtitle "$_backtitle" --title " Opciones para la imagen $(image_name "${IMAGE[$i]}") " \
+		--checklist "" $((_H/2)) $((_W/2)) 8 \
+		"privileged" " " off \
+		"CAP_SYS_ADMIN" " " off \
+		"name"	"Give a name to the container" off \
+		"v" "Mount a volume" off \
+		"d" "Detach" off \
+		"i" "Interactive" on \
+		"t" "Tty" on 2> $tempfile
+	get_result $?
 
-get_result $?
+	declare -a OPTIONS=( $(cat "$tempfile") )
 
-IMAGE=$(cat "$tempfile")
+	while [ $j -ne ${#OPTIONS[*]} ]; do
+		case ${OPTIONS[$j]} in
+			privileged)	COMMAND="$COMMAND --privileged"
+					;;
+			CAP_SYS_ADMIN)	COMMAND="$COMMAND -e CAP_SYS_ADMIN"
+					;;
+			name)		name_form
+					[[ ! -z $CON_NAME ]] && COMMAND="$COMMAND --name $CON_NAME"
+					;;
+			d)		COMMAND="$COMMAND -d"
+					;;
+			i)		COMMAND="$COMMAND -i"
+					;;
+			t)		COMMAND="$COMMAND -t"
+					;;
+			v)		volume_form
+					COMMAND="$COMMAND $VOLUME"
+					;;
+		esac
+		(( j++ ))
+	done
 
-$DIALOG --clear --backtitle "$_backtitle" --title " Opciones " \
-	--checklist "" $((_H/2)) $((_W/2)) 8 \
-	"privileged" " " off \
-	"CAP_SYS_ADMIN" " " off \
-	"name"	"Give a name to the volume" off \
-	"v" "Mount a volume" off \
-	"i" "Interactive" on \
-	"t" "Tty" on 2> $tempfile
+	COMMAND="$COMMAND ${IMAGE[$i]}"
 
-get_result $?
-
-declare -a OPTIONS=( $(cat "$tempfile") )
-
-let j=0
-while [ $j -ne ${#OPTIONS[*]} ]; do
-	case ${OPTIONS[$j]} in
-		privileged)	COMMAND="$COMMAND --privileged"
-				;;
-		CAP_SYS_ADMIN)	COMMAND="$COMMAND -e CAP_SYS_ADMIN"
-				;;
-		name)		name_form
-				COMMAND="$COMMAND --name $CON_NAME"
-				;;
-		i)		COMMAND="$COMMAND -i"
-				;;
-		t)		COMMAND="$COMMAND -t"
-				;;
-		v)		volume_form
-				COMMAND="$COMMAND $VOLUME"
-				;;
-	esac
-	(( j++ ))
-done
-
-COMMAND="$COMMAND $IMAGE"
-
-$DIALOG --clear --backtitle "$_backtitle" --title " Comando " \
-	--inputbox "¿Quieres ejecutar un comando remoto?
+	$DIALOG --clear --backtitle "$_backtitle" --title " Comando " \
+		--inputbox "¿Quieres ejecutar un comando remoto?
 Por defecto se ejecuta un shell de bash." $((_H/2)) $((_W/2)) "/bin/bash" 2> $tempfile
+	get_result $?
 
-get_result $?
-
-COMMAND="$COMMAND $(cat $tempfile)"
-
-$COMMAND
-
+	COMMAND="$COMMAND $(cat $tempfile)"
+	echo "Result for running container $CON_NAME" >>"$INPUT_F"
+	$COMMAND >>"$INPUT_F" 2>&1
+	echo "---------------------------------------------------" >>"$INPUT_F"
+	unset OPTIONS COMMAND VOLUME CON_NAME
+	(( i++ ))
+done
+$DIALOG --clear --backtitle "$_backtitle" --title " docker_run result " \
+	--textbox "$INPUT_F" 0 0
